name: Examples Build Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # Nightly at 00:00
  workflow_dispatch: { }

jobs:
  examples-build-test:

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Scoop Installer
      uses: MinoruSekine/setup-scoop@v1
    - name: Scoop Bucket Add
      run: scoop bucket add crystal-preview https://github.com/neatorobito/scoop-crystal
    - name: Scoop Crystal Install
      run: scoop install crystal
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - run: crystal build -o simple_window.exe examples\simple_window\window.cr
